### ISSUE TITLE
Installation error: Can not install using npm

### ISSUE THREAD

**Issue by tom-avilius** [tuj84257/electron-bottom-window#1]
### Version Info
node => v18.14.0
npm => v6.14.18
node-gyp => v9.3.1
electron => v23.1.1
electron-squirrel-startup => v1.0.0
windows 10 => build 19045

### Error log

npm i electron-bottom-window

> ref-napi@3.0.3 install D:\Aaarsh\javascript\splash\node_modules\ref-napi
> node-gyp-build

> win-setwindowpos@2.1.0 install D:\Aaarsh\javascript\splash\node_modules\win-setwindowpos
> node-gyp rebuild

D:\Aaarsh\javascript\splash\node_modules\win-setwindowpos>if not defined npm_config_node_gyp (node "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
(node:4048) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Traceback (most recent call last):
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aaars\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Aaarsh\javascript\splash\node_modules\win-setwindowpos
gyp ERR! node -v v18.14.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
npm WARN splash@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-debian@3.1.0 (node_modules\electron-installer-debian):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-debian@3.1.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-redhat@3.3.0 (node_modules\electron-installer-redhat):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-redhat@3.3.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! win-setwindowpos@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the win-setwindowpos@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aaars\AppData\Roaming\npm-cache\_logs\2023-03-03T13_20_56_513Z-debug.log

### How to replicate the error

- Initialize an empty repository using npm init.
- (maybe optional) run `npm install electron`
- run `npm install electron-bottom-window`

I desperately need help regarding this. Or, perhaps some suggestions to achieve a bottom most electron window. I would be grateful if you could respond.

**Comment by tuj84257** [comment]
Hi @tom-avilius, I think you need to install the MS Build Tools prior to install the necessary packages. [This](https://stackoverflow.com/questions/25506178/getting-msbuild-exe-without-installing-visual-studio) StackOverflow question might help you with the installation procedure.

**Comment by tom-avilius** [comment]
Greetings. Thankyou for your response. I believe python 3.11 was the issue as it is not supported by node-gyp. Python 2.7 is working fine and the installation proceeds as expected.
